### PR TITLE
feat(toolchain): e2e tests for JavaScript codegen

### PR DESCRIPTION
**Pull request by davemneo**
## Test plan
    yarn jest buildCommand

## dev testing test... 
    yarn build
    yarn neo-one reset --static-neo-one && yarn neo-one start server --static-neo-one --debug
    yarn neo-one build

## Description of the Change
Support compiling to JavaScript by:
updating webpack configuration to compile to JavaScript
update buildCommand tests

### CODE REVIEW

**Comment by davemneo** [comment]
Lint is getting a bunch of

` TS2741: Property '[one0]' is missing in type `

**Comment by dicarlo2** [comment]
> TS2741: Property '[one0]' is missing in type

This is the same problem as before - you need to add the ignore in the root tsconfig.

**Comment by davemneo** [comment]
bors try

**Pull request merged**
